import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
// PageLoader is intentionally not mounted here — loader will be handled
// directly on the landing page to allow the landing content to render
// behind the frosted-glass overlay. The original component remains in
// `src/components/PageLoader.tsx` but is not used so it can be restored
// later if desired.
import CursorGlow from "../components/CursorGlow";
import Footer from "./components/Footer";
import AlignGlow from "./components/AlignGlow";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* OverlayLoaderController removed */}
        <div id="page-cloak">
          <Navbar />
          <div style={{ background: 'linear-gradient(90deg, #0B132B 0%, #1B3A2D 100%)', minHeight: 'calc(100vh - 120px)' }}>
            <main className="w-full min-h-screen flex flex-col">{children}</main>
          </div>
          <CursorGlow />
          <AlignGlow />
          <Footer />
        </div>
        <link href="https://fonts.googleapis.com/css2?family=Syne:wght@400;700&display=swap" rel="stylesheet" />
      </body>
    </html>
  );
}
