import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import VideoBackground from "../components/VideoBackground";
import PageLoader from "../components/PageLoader";
import CursorGlow from "../components/CursorGlow";
import PageCloakController from "../components/PageCloakController";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          {/* Global page loader for route transitions */}
        {/* Controller to ensure the server-side cloak is removed on non-landing routes */}
        <PageCloakController />
        <PageLoader />
  {/* Cloak wrapper: initially hidden server-side to prevent content flash.*/}
  <div id="page-cloak" className="page-loader-hidden">
    {/* Video background sits behind everything except the green info bar */}
    <VideoBackground />
    <Navbar />
    <main className="w-full min-h-screen flex flex-col">{children}</main>
    {/* Cursor glow: mounted here so it covers navbar, hero, timeline only on landing page */}
    <CursorGlow />
  </div>
        <link href="https://fonts.googleapis.com/css2?family=Syne:wght@400;700&display=swap" rel="stylesheet" />
      </body>
    </html>
  );
}
